	nios_system u0 (
		.clk_clk                  (<connected-to-clk_clk>),                  //               clk.clk
		.is_new_game_start_export (<connected-to-is_new_game_start_export>), // is_new_game_start.export
		.keycode_export           (<connected-to-keycode_export>),           //           keycode.export
		.keycode0_export          (<connected-to-keycode0_export>),          //          keycode0.export
		.keycode1_export          (<connected-to-keycode1_export>),          //          keycode1.export
		.keycode2_export          (<connected-to-keycode2_export>),          //          keycode2.export
		.otg_hpi_address_export   (<connected-to-otg_hpi_address_export>),   //   otg_hpi_address.export
		.otg_hpi_cs_export        (<connected-to-otg_hpi_cs_export>),        //        otg_hpi_cs.export
		.otg_hpi_data_in_port     (<connected-to-otg_hpi_data_in_port>),     //      otg_hpi_data.in_port
		.otg_hpi_data_out_port    (<connected-to-otg_hpi_data_out_port>),    //                  .out_port
		.otg_hpi_r_export         (<connected-to-otg_hpi_r_export>),         //         otg_hpi_r.export
		.otg_hpi_reset_export     (<connected-to-otg_hpi_reset_export>),     //     otg_hpi_reset.export
		.otg_hpi_w_export         (<connected-to-otg_hpi_w_export>),         //         otg_hpi_w.export
		.position0_export         (<connected-to-position0_export>),         //         position0.export
		.position1_export         (<connected-to-position1_export>),         //         position1.export
		.position10_export        (<connected-to-position10_export>),        //        position10.export
		.position11_export        (<connected-to-position11_export>),        //        position11.export
		.position12_export        (<connected-to-position12_export>),        //        position12.export
		.position13_export        (<connected-to-position13_export>),        //        position13.export
		.position14_export        (<connected-to-position14_export>),        //        position14.export
		.position15_export        (<connected-to-position15_export>),        //        position15.export
		.position16_export        (<connected-to-position16_export>),        //        position16.export
		.position17_export        (<connected-to-position17_export>),        //        position17.export
		.position18_export        (<connected-to-position18_export>),        //        position18.export
		.position19_export        (<connected-to-position19_export>),        //        position19.export
		.position2_export         (<connected-to-position2_export>),         //         position2.export
		.position20_export        (<connected-to-position20_export>),        //        position20.export
		.position3_export         (<connected-to-position3_export>),         //         position3.export
		.position4_export         (<connected-to-position4_export>),         //         position4.export
		.position5_export         (<connected-to-position5_export>),         //         position5.export
		.position6_export         (<connected-to-position6_export>),         //         position6.export
		.position7_export         (<connected-to-position7_export>),         //         position7.export
		.position8_export         (<connected-to-position8_export>),         //         position8.export
		.position9_export         (<connected-to-position9_export>),         //         position9.export
		.reset_reset_n            (<connected-to-reset_reset_n>),            //             reset.reset_n
		.sdram_clk_clk            (<connected-to-sdram_clk_clk>),            //         sdram_clk.clk
		.sdram_wire_addr          (<connected-to-sdram_wire_addr>),          //        sdram_wire.addr
		.sdram_wire_ba            (<connected-to-sdram_wire_ba>),            //                  .ba
		.sdram_wire_cas_n         (<connected-to-sdram_wire_cas_n>),         //                  .cas_n
		.sdram_wire_cke           (<connected-to-sdram_wire_cke>),           //                  .cke
		.sdram_wire_cs_n          (<connected-to-sdram_wire_cs_n>),          //                  .cs_n
		.sdram_wire_dq            (<connected-to-sdram_wire_dq>),            //                  .dq
		.sdram_wire_dqm           (<connected-to-sdram_wire_dqm>),           //                  .dqm
		.sdram_wire_ras_n         (<connected-to-sdram_wire_ras_n>),         //                  .ras_n
		.sdram_wire_we_n          (<connected-to-sdram_wire_we_n>),          //                  .we_n
		.position21_export        (<connected-to-position21_export>),        //        position21.export
		.position22_export        (<connected-to-position22_export>),        //        position22.export
		.position23_export        (<connected-to-position23_export>),        //        position23.export
		.position24_export        (<connected-to-position24_export>),        //        position24.export
		.position25_export        (<connected-to-position25_export>),        //        position25.export
		.position26_export        (<connected-to-position26_export>),        //        position26.export
		.position27_export        (<connected-to-position27_export>),        //        position27.export
		.position28_export        (<connected-to-position28_export>),        //        position28.export
		.position29_export        (<connected-to-position29_export>),        //        position29.export
		.position30_export        (<connected-to-position30_export>),        //        position30.export
		.position31_export        (<connected-to-position31_export>),        //        position31.export
		.position32_export        (<connected-to-position32_export>),        //        position32.export
		.position33_export        (<connected-to-position33_export>),        //        position33.export
		.position34_export        (<connected-to-position34_export>),        //        position34.export
		.position35_export        (<connected-to-position35_export>),        //        position35.export
		.position36_export        (<connected-to-position36_export>)         //        position36.export
	);

