#ifndef IO_HANDLER_H_
#define IO_HANDLER_H_
#include "alt_types.h"
#include "system.h"

// These addresses are defined in system.h generated by Eclipse, and they
// should have been matched to the addresses shown in Qsys.
// If for any reason they are not correctly defined, you can replace these
// with the addresses you read in Qsys.
#define otg_hpi_address			(volatile int*) 	OTG_HPI_ADDRESS_BASE
#define otg_hpi_data			(volatile int*)	    OTG_HPI_DATA_BASE
#define otg_hpi_r				(volatile char*)	OTG_HPI_R_BASE
#define otg_hpi_cs				(volatile char*)	OTG_HPI_CS_BASE //FOR SOME REASON CS BASE BEHAVES WEIRDLY MIGHT HAVE TO SET MANUALLY

void IO_write(alt_u8 Address, alt_u16 Data);
#define otg_hpi_w				(volatile char*)	OTG_HPI_W_BASE
#define otg_hpi_reset			(volatile char*)	OTG_HPI_RESET_BASE
#define keycode_base			(volatile char*)	KEYCODE_BASE
#define keycode_base0			(volatile char*)	0x00000040
#define keycode_base1			(volatile char*)	0x00000030
#define keycode_base2			(volatile char*)	0x00000020
#define position_0				(volatile int*)	0x000001a0
#define position_1				(volatile int*)	0x00000190
#define position_2				(volatile int*)	0x00000180
#define position_3				(volatile int*)	0x00000170
#define position_4				(volatile int*)	0x00000160
#define position_5				(volatile int*)	0x00000150
#define position_6				(volatile int*)	0x00000140
#define position_7				(volatile int*)	0x00000130
#define position_8				(volatile int*)	0x00000120
#define position_9				(volatile int*)	0x00000110
#define position_10				(volatile int*)	0x00000100
#define position_11				(volatile int*)	0x000000f0
#define position_12				(volatile int*)	0x000000e0
#define position_13				(volatile int*)	0x000000d0
#define position_14				(volatile int*)	0x000000c0
#define position_15				(volatile int*)	0x000000a0
#define position_16				(volatile int*)	0x00000090
#define position_17				(volatile int*)	0x00000080
#define position_18				(volatile int*)	0x00000070
#define position_19				(volatile int*)	0x00000060
#define position_20				(volatile int*)	0x00000050
#define is_new_game_start		(volatile int*)	0x000001b0


#define position_21				(volatile int*)	0x000002a0
#define position_22				(volatile int*)	0x00000290
#define position_23				(volatile int*)	0x00000280
#define position_24				(volatile int*)	0x00000270
#define position_25				(volatile int*)	0x00000260
#define position_26				(volatile int*)	0x00000250
#define position_27				(volatile int*)	0x00000240
#define position_28				(volatile int*)	0x00000230
#define position_29				(volatile int*)	0x00000220
#define position_30				(volatile int*)	0x00000210
#define position_31				(volatile int*)	0x00000200
#define position_32				(volatile int*)	0x000001f0
#define position_33				(volatile int*)	0x000001e0
#define position_34				(volatile int*)	0x000001d0
#define position_35				(volatile int*)	0x000001c0
#define position_36				(volatile int*)	0x000002b0
alt_u16 IO_read(alt_u8 Address);
void IO_init(void);


#endif
